### PR TITLE
Add LGTM code quality badges

### PR DESCRIPTION
**Pull request by xcorail**
Hi there!

I thought you might be interested in adding these [LGTM code quality badges](https://lgtm.com/projects/g/ppwwyyxx/OpenPano/ci/#badges) to your project, to show how you care about code quality and encourage contributors to do the same.
To get an idea of the analyses reflected by these grades, check the [alerts discovered by LGTM](https://lgtm.com/projects/g/ppwwyyxx/OpenPano).

N.B.: I am on the team behind LGTM.com, I'd appreciate your feedback on this initiative, whether you're interested or not, if you find time to drop me a line. Thanks.

### CODE REVIEW

**Comment by ppwwyyxx** [comment]
Thanks for the suggestions. I take a look at the alerts. It does find something useful but I'd rather ignore most of them. For example I prefer to not do the int->size_t casting if I know there won't be any overflow.

I found another issue with another of my projects: https://github.com/tensorpack/tensorpack. It was moved from ppwwyyxx/tensorpack, and it seems like LGTM cannot identify this. It can only shows commits before the move at https://lgtm.com/projects/g/ppwwyyxx/tensorpack .

**Comment by xcorail** [comment]
Hello @ppwwyyxx 

> It does find something useful but I'd rather ignore most of them

* Note that our ranking of issues is a complex heuristic, based on several factors (introduced by you, introduced in files that you code in, severity, ...). One of this factor is the fix ratio in this project. Meaning that issues you use to fix are ranked higher that issues you don't seem to care about. So if you just don't fix these issues, they will be ranked lower and lower with time.
* If in this particular part of the code you are sure that there won't be any overflow, just suppress the alert by adding a `//lgtm` comment. More details [here](https://lgtm.com/help/lgtm/alert-suppression)   

> I found another issue with another of my projects: https://github.com/tensorpack/tensorpack. 

Did you try to add it at https://lgtm.com/dashboard?
 
Cheers, thanks a lot for the feedback

**Comment by ppwwyyxx** [comment]
Adding https://github.com/tensorpack/tensorpack to the dashboard will only give me "ppwwyyxx/tensorpack", which does not have any of the new commits after the move.

**Comment by xcorail** [comment]
Hello @ppwwyyxx 

* The commits are actually taken from tensorpack/tensorpack, see the list of commits by scrolling down on the main page. And when you click on the GitHub icon, it actually goes to tensorpack/tensorpack. **Do you want us to rename the project on LGTM?**
* However there is a build failure

`
[2018-09-15 07:33:08] [build]     Complete output from command python setup.py egg_info:
[2018-09-15 07:33:08] [build]     You need to install libcap development headers to build this module
[2018-09-15 07:33:08] [build]     
[2018-09-15 07:33:08] [build]     ----------------------------------------
[2018-09-15 07:33:08] [build] Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-svMEXT/python-prctl/
`

You need to add libcap installation to your [LGTM configuration file](https://lgtm.com/help/lgtm/python-extraction). **Do you want me to propose a PR to show you how it's done?**

**Comment by ppwwyyxx** [comment]
Oh sorry I didn't notice that.
Actually the package `python-prctl` which depends on libcap is only an optional dependency. The library is fully functional without it. But I guess the package extraction heuristics will take everything it sees. Thanks!

**Comment by xcorail** [comment]
So, do you want me to propose a PR for fixing the build, or do you want to try it out by yourself?

**Comment by xcorail** [comment]
Hey @ppwwyyxx 

Just wanted to let you know that during 6 weeks, for each LGTM alert fixed, we'll make a donation to WWF. You can also win a free ticket to GitHub Universe, with travel and accommodation. Details here: https://competitions.lgtm.com/ghu-2018

**Pull request closed without merging**
